import { useState, useEffect } from 'react';
import { collection, addDoc, getDocs, query, orderBy, Timestamp } from 'firebase/firestore';
import { db } from '@/lib/firebase';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog';
import { Card, CardContent } from '@/components/ui/card';
import { toast } from 'react-hot-toast';
import { FileText, Plus, Download, Eye } from 'lucide-react';

interface Certificate {
  id: string;
  employeeId: string;
  employeeName: string;
  employeeCode: string;
  designation: string;
  department: string;
  dateOfJoining: string;
  dateOfRelieving: string;
  certificateContent: string;
  generatedBy: string;
  generatedDate: string;
  createdAt: Date;
}

export const ExperienceCertificate = () => {
  const [certificates, setCertificates] = useState<Certificate[]>([]);
  const [clearances, setClearances] = useState<any[]>([]);
  const [isDialogOpen, setIsDialogOpen] = useState(false);
  const [viewDialogOpen, setViewDialogOpen] = useState(false);
  const [selectedCertificate, setSelectedCertificate] = useState<Certificate | null>(null);
  const [loading, setLoading] = useState(false);
  
  const [formData, setFormData] = useState({
    employeeId: '',
    designation: '',
    department: '',
    dateOfJoining: '',
    dateOfRelieving: '',
    generatedBy: '',
    additionalContent: ''
  });

  useEffect(() => {
    fetchCertificates();
    fetchClearances();
  }, []);

  const fetchClearances = async () => {
    try {
      const snapshot = await getDocs(collection(db, 'clearances'));
      const data = snapshot.docs.map(doc => ({
        id: doc.id,
        ...doc.data()
      }));
      setClearances(data.filter((c: any) => c.overallStatus === 'completed'));
    } catch (error) {
      console.error('Error fetching clearances:', error);
    }
  };

  const fetchCertificates = async () => {
    try {
      const q = query(collection(db, 'certificates'), orderBy('createdAt', 'desc'));
      const snapshot = await getDocs(q);
      const data = snapshot.docs.map(doc => ({
        id: doc.id,
        ...doc.data(),
        createdAt: doc.data().createdAt?.toDate() || new Date()
      })) as Certificate[];
      setCertificates(data);
    } catch (error) {
      console.error('Error fetching certificates:', error);
      toast.error('Failed to fetch certificates');
    }
  };

  const generateCertificateContent = (data: any) => {
    return `
EXPERIENCE CERTIFICATE

TO WHOM IT MAY CONCERN

This is to certify that ${data.employeeName} (Employee Code: ${data.employeeCode}) has worked with our organization as ${data.designation} in the ${data.department} department.

Period of Employment:
From: ${new Date(data.dateOfJoining).toLocaleDateString('en-IN', { day: '2-digit', month: 'long', year: 'numeric' })}
To: ${new Date(data.dateOfRelieving).toLocaleDateString('en-IN', { day: '2-digit', month: 'long', year: 'numeric' })}

During their tenure with us, ${data.employeeName} has demonstrated professionalism, dedication, and strong work ethics. We found them to be sincere, hardworking, and committed to their responsibilities.

${data.additionalContent || ''}

We wish them all the best in their future endeavors.

Generated By: ${data.generatedBy}
Date: ${new Date(data.generatedDate).toLocaleDateString('en-IN')}

For [Company Name]
Authorized Signatory
    `.trim();
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);

    try {
      const selectedClearance = clearances.find(c => c.employeeId === formData.employeeId);
      
      if (!selectedClearance) {
        toast.error('Clearance not found');
        return;
      }

      const generatedDate = new Date().toISOString();
      const certificateContent = generateCertificateContent({
        ...formData,
        employeeName: selectedClearance.employeeName,
        employeeCode: selectedClearance.employeeCode,
        generatedDate
      });

      await addDoc(collection(db, 'certificates'), {
        employeeId: formData.employeeId,
        employeeName: selectedClearance.employeeName,
        employeeCode: selectedClearance.employeeCode,
        designation: formData.designation,
        department: formData.department,
        dateOfJoining: formData.dateOfJoining,
        dateOfRelieving: formData.dateOfRelieving,
        certificateContent,
        generatedBy: formData.generatedBy,
        generatedDate,
        createdAt: Timestamp.now()
      });

      toast.success('Certificate generated successfully');
      setIsDialogOpen(false);
      resetForm();
      fetchCertificates();
    } catch (error) {
      console.error('Error generating certificate:', error);
      toast.error('Failed to generate certificate');
    } finally {
      setLoading(false);
    }
  };

  const resetForm = () => {
    setFormData({
      employeeId: '',
      designation: '',
      department: '',
      dateOfJoining: '',
      dateOfRelieving: '',
      generatedBy: '',
      additionalContent: ''
    });
  };

  const handleDownload = (certificate: Certificate) => {
    const blob = new Blob([certificate.certificateContent], { type: 'text/plain' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `Experience_Certificate_${certificate.employeeCode}.txt`;
    document.body.appendChild(a);
    a.click();
    window.URL.revokeObjectURL(url);
    document.body.removeChild(a);
    toast.success('Certificate downloaded');
  };

  const viewCertificate = (certificate: Certificate) => {
    setSelectedCertificate(certificate);
    setViewDialogOpen(true);
  };

  return (
    <div className="space-y-4">
      <div className="flex justify-between items-center">
        <div>
          <h3 className="text-lg font-semibold">Experience Certificate Generation</h3>
          <p className="text-sm text-muted-foreground">Generate and manage experience certificates</p>
        </div>
        <Dialog open={isDialogOpen} onOpenChange={setIsDialogOpen}>
          <DialogTrigger asChild>
            <Button>
              <Plus className="mr-2 h-4 w-4" />
              Generate Certificate
            </Button>
          </DialogTrigger>
          <DialogContent className="max-w-2xl">
            <DialogHeader>
              <DialogTitle>Generate Experience Certificate</DialogTitle>
            </DialogHeader>
            <form onSubmit={handleSubmit} className="space-y-4">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div className="col-span-2">
                  <Label htmlFor="employee">Employee *</Label>
                  <Select
                    value={formData.employeeId}
                    onValueChange={(value) => setFormData({ ...formData, employeeId: value })}
                    required
                  >
                    <SelectTrigger>
                      <SelectValue placeholder="Select employee" />
                    </SelectTrigger>
                    <SelectContent>
                      {clearances.map(c => (
                        <SelectItem key={c.employeeId} value={c.employeeId}>
                          {c.employeeName} - {c.employeeCode}
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>

                <div>
                  <Label htmlFor="designation">Designation *</Label>
                  <Input
                    id="designation"
                    value={formData.designation}
                    onChange={(e) => setFormData({ ...formData, designation: e.target.value })}
                    placeholder="Enter designation"
                    required
                  />
                </div>

                <div>
                  <Label htmlFor="department">Department *</Label>
                  <Input
                    id="department"
                    value={formData.department}
                    onChange={(e) => setFormData({ ...formData, department: e.target.value })}
                    placeholder="Enter department"
                    required
                  />
                </div>

                <div>
                  <Label htmlFor="dateOfJoining">Date of Joining *</Label>
                  <Input
                    id="dateOfJoining"
                    type="date"
                    value={formData.dateOfJoining}
                    onChange={(e) => setFormData({ ...formData, dateOfJoining: e.target.value })}
                    required
                  />
                </div>

                <div>
                  <Label htmlFor="dateOfRelieving">Date of Relieving *</Label>
                  <Input
                    id="dateOfRelieving"
                    type="date"
                    value={formData.dateOfRelieving}
                    onChange={(e) => setFormData({ ...formData, dateOfRelieving: e.target.value })}
                    required
                  />
                </div>

                <div className="col-span-2">
                  <Label htmlFor="generatedBy">Generated By *</Label>
                  <Input
                    id="generatedBy"
                    value={formData.generatedBy}
                    onChange={(e) => setFormData({ ...formData, generatedBy: e.target.value })}
                    placeholder="Name of the person generating certificate"
                    required
                  />
                </div>

                <div className="col-span-2">
                  <Label htmlFor="additionalContent">Additional Content (Optional)</Label>
                  <Textarea
                    id="additionalContent"
                    value={formData.additionalContent}
                    onChange={(e) => setFormData({ ...formData, additionalContent: e.target.value })}
                    placeholder="Any additional remarks to include in the certificate"
                    rows={4}
                  />
                </div>
              </div>

              <div className="flex justify-end gap-2">
                <Button type="button" variant="outline" onClick={() => setIsDialogOpen(false)}>
                  Cancel
                </Button>
                <Button type="submit" disabled={loading}>
                  {loading ? 'Generating...' : 'Generate Certificate'}
                </Button>
              </div>
            </form>
          </DialogContent>
        </Dialog>
      </div>

      <div className="grid gap-4">
        {certificates.length === 0 ? (
          <Card>
            <CardContent className="pt-6 text-center text-muted-foreground">
              No certificates generated
            </CardContent>
          </Card>
        ) : (
          certificates.map((certificate) => (
            <Card key={certificate.id}>
              <CardContent className="pt-6">
                <div className="flex justify-between items-start">
                  <div className="space-y-2">
                    <h4 className="font-semibold">{certificate.employeeName}</h4>
                    <p className="text-sm text-muted-foreground">
                      {certificate.employeeCode} | {certificate.designation} | {certificate.department}
                    </p>
                    <p className="text-sm">
                      <span className="font-medium">Employment Period:</span>{' '}
                      {new Date(certificate.dateOfJoining).toLocaleDateString()} to{' '}
                      {new Date(certificate.dateOfRelieving).toLocaleDateString()}
                    </p>
                    <p className="text-sm text-muted-foreground">
                      Generated by {certificate.generatedBy} on{' '}
                      {new Date(certificate.generatedDate).toLocaleDateString()}
                    </p>
                  </div>
                  <div className="flex gap-2">
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={() => viewCertificate(certificate)}
                    >
                      <Eye className="h-4 w-4 mr-2" />
                      View
                    </Button>
                    <Button
                      variant="default"
                      size="sm"
                      onClick={() => handleDownload(certificate)}
                    >
                      <Download className="h-4 w-4 mr-2" />
                      Download
                    </Button>
                  </div>
                </div>
              </CardContent>
            </Card>
          ))
        )}
      </div>

      {/* View Certificate Dialog */}
      <Dialog open={viewDialogOpen} onOpenChange={setViewDialogOpen}>
        <DialogContent className="max-w-3xl max-h-[90vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle>Experience Certificate</DialogTitle>
          </DialogHeader>
          {selectedCertificate && (
            <Card>
              <CardContent className="pt-6">
                <pre className="whitespace-pre-wrap font-mono text-sm p-4 bg-muted rounded-lg">
                  {selectedCertificate.certificateContent}
                </pre>
              </CardContent>
            </Card>
          )}
        </DialogContent>
      </Dialog>
    </div>
  );
};
